[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/who-we-are/manuel-suter/"
to = "/who-we-are/members/manuel-suter/"

[[redirects]]
from = "/who-we-are/javier-galan-cubillo/"
to = "/who-we-are/members/javier-galan-cubillo/"

[[redirects]]
from = "/members/julia-bruckner/"
to = "/who-we-are/members/julia-bruckner/"

[[redirects]]
from = "/team/"
to = "/who-we-are/members/"

[[redirects]]
from = "/members/maike-grossen/"
to = "/who-we-are/members/maike-grossen/"

[[redirects]]
from = "/who-we-are/lotte-levelt/"
to = "/who-we-are/members/lotte-levelt/"

[[redirects]]
from = "/history-purpose/"
to = "/who-we-are/overview/"

[[redirects]]
from = "/members/editors/"
to = "/who-we-are/members/editors/"

[[redirects]]
from = "/who-we-are/lisa-sophie-welsleben/"
to = "/who-we-are/members/lisa-sophie-welsleben/"

[[redirects]]
from = "/who-we-are/editors/"
to = "/who-we-are/members/editors/"

[[redirects]]
from = "/who-we-are/jessica-jungell-michelsson/"
to = "/who-we-are/members/jessica-jungell-michelsson/"

[[redirects]]
from = "/who-we-are/christian-gnepke/"
to = "/who-we-are/members/christian-gnepke/"

[[redirects]]
from = "/who-we-are/anna-burch/"
to = "/who-we-are/members/anna-burch/"

[[redirects]]
from = "/overview/"
to = "/who-we-are/overview/"

[[redirects]]
from = "/who-we-are/isaac-ortega-alvarado/"
to = "/who-we-are/members/isaac-ortega-alvarado/"

[[redirects]]
from = "/who-we-are/katrin-pakizer/"
to = "/who-we-are/members/katrin-pakizer/"

[[redirects]]
from = "/who-we-are/marie-julie-de-bruyne/"
to = "/who-we-are/members/marie-julie-de-bruyne/"

[[redirects]]
from = "/agenda/2026/monthly-network-webinar-2-march-1/"
to = "/agenda/2026/monthly-network-webinar-april-2026/"

[[redirects]]
from = "/who-we-are/carys-egan-wyer/"
to = "/who-we-are/members/carys-egan-wyer/"

[[redirects]]
from = "/agenda/2026/monthly-network-webinar-9-feb-1/"
to = "/agenda/2026/monthly-network-webinar-2-march/"

[[redirects]]
from = "/who-we-are/adina-arth/"
to = "/who-we-are/members/adina-arth/"

[[redirects]]
from = "/who-we-are/isabel-pacheco/"
to = "/who-we-are/members/isabel-pacheco/"

[[redirects]]
from = "/agenda/2025/monthly-network-webinar-sept-25-1/"
to = "/agenda/2025/monthly-network-webinar-25-oct/"

[[redirects]]
from = "/who-we-are/maike-grossen/"
to = "/who-we-are/members/maike-grossen/"

[[redirects]]
from = "/who-we-are/benjamin-combes/"
to = "/who-we-are/members/benjamin-combes/"

[[redirects]]
from = "/who-we-are/jean-philippe-decka/"
to = "/who-we-are/members/jean-philippe-decka/"

[[redirects]]
from = "/who-we-are/fanny-dethier/"
to = "/who-we-are/members/fanny-dethier/"

[[redirects]]
from = "/members/benjamin-combes/"
to = "/who-we-are/members/benjamin-combes/"

[[redirects]]
from = "/who-we-are/manon-villers/"
to = "/who-we-are/members/manon-villers/"

[[redirects]]
from = "/get-in-touch/"
to = "/contact/"

[[redirects]]
from = "/who-we-are/nicholas-owen/"
to = "/who-we-are/members/nicholas-owen/"

[[redirects]]
from = "/who-we-are/leonard-creutzburg/"
to = "/who-we-are/members/leonard-creutzburg/"

[[redirects]]
from = "/agenda/2025/monthly-network-webinar/"
to = "/agenda/2025/monthly-network-webinar-sept-25/"

[[redirects]]
from = "/who-we-are/laura-beyeler/"
to = "/who-we-are/members/laura-beyeler/"

[[redirects]]
from = "/members/"
to = "/who-we-are/members/"

[[redirects]]
from = "/who-we-are/indra-da-silva-wagner/"
to = "/who-we-are/members/indra-da-silva-wagner/"

[[redirects]]
from = "/who-we-are/tobias-froese/"
to = "/who-we-are/members/tobias-froese/"

[[redirects]]
from = "/agenda/2025/monthly-network-webinar-sept-25-1-1/"
to = "/agenda/2025/monthly-network-webinar-25-nov/"

[[redirects]]
from = "/who-we-are/valentin-sagvosdkin/"
to = "/who-we-are/members/valentin-sagvosdkin/"

[[redirects]]
from = "/who-we-are/iana-nesterova/"
to = "/who-we-are/members/iana-nesterova/"

[[redirects]]
from = "/who-we-are/cedric-gossart/"
to = "/who-we-are/members/cedric-gossart/"

[[redirects]]
from = "/who-we-are/johannes-matschewsky/"
to = "/who-we-are/members/johannes-matschewsky/"

[[redirects]]
from = "/members/marie-julie-de-bruyne/"
to = "/who-we-are/members/marie-julie-de-bruyne/"

[[redirects]]
from = "/who-we-are/maren-kropfeld/"
to = "/who-we-are/members/maren-kropfeld/"

[[redirects]]
from = "/who-we-are/tobias-vogel/"
to = "/who-we-are/members/tobias-vogel/"

[[redirects]]
from = "/members/laura-niessen/"
to = "/who-we-are/members/laura-niessen/"

[[redirects]]
from = "/who-we-are/julia-bruckner/"
to = "/who-we-are/members/julia-bruckner/"

[[redirects]]
from = "/who-we-are/oksana-mont/"
to = "/who-we-are/members/oksana-mont/"

[[redirects]]
from = "/who-we-are/lucy-chamberlin/"
to = "/who-we-are/members/lucy-chamberlin/"

[[redirects]]
from = "/who-we-are/noah-labinaz/"
to = "/who-we-are/members/noah-labinaz/"

[[redirects]]
from = "/who-we-are/theo-visbecq/"
to = "/who-we-are/members/theo-visbecq/"

[[redirects]]
from = "/agenda/2025/monthly-network-webinar-25-dec-1/"
to = "/agenda/2026/monthly-network-webinar-9-feb/"

[[redirects]]
from = "/who-we-are/josefine-henman/"
to = "/who-we-are/members/josefine-henman/"

[[redirects]]
from = "/who-we-are/fernanda-godoy-leon/"
to = "/who-we-are/members/fernanda-godoy-leon/"

[[redirects]]
from = "/who-we-are/laura-niessen/"
to = "/who-we-are/members/laura-niessen/"

[[redirects]]
from = "/team/editors/"
to = "/who-we-are/members/editors/"

